python main.py train -d "./experiments/De ppo normal_sampled" -cd "/AttractiveSector_5D" -c exp1
python main.py train -d "./experiments/De ppo normal_sampled" -cd "/AttractiveSector_10D" -c exp2
python main.py train -d "./experiments/De ppo normal_sampled" -cd "/AttractiveSector_20D" -c exp3
python main.py train -d "./experiments/De ppo normal_sampled" -cd "/BuecheRastrigin_5D" -c exp4
python main.py train -d "./experiments/De ppo normal_sampled" -cd "/BuecheRastrigin_10D" -c exp5
python main.py train -d "./experiments/De ppo normal_sampled" -cd "/BuecheRastrigin_20D" -c exp6
python main.py train -d "./experiments/De ppo normal_sampled" -cd "/CompositeGR_5D" -c exp7
python main.py train -d "./experiments/De ppo normal_sampled" -cd "/CompositeGR_10D" -c exp8
python main.py train -d "./experiments/De ppo normal_sampled" -cd "/CompositeGR_20D" -c exp9
python main.py train -d "./experiments/De ppo normal_sampled" -cd "/DifferentPowers_5D" -c exp10
python main.py train -d "./experiments/De ppo normal_sampled" -cd "/DifferentPowers_10D" -c exp11
python main.py train -d "./experiments/De ppo normal_sampled" -cd "/DifferentPowers_20D" -c exp12
python main.py train -d "./experiments/De ppo normal_sampled" -cd "/LinearSlope_5D" -c exp13
python main.py train -d "./experiments/De ppo normal_sampled" -cd "/LinearSlope_10D" -c exp14
python main.py train -d "./experiments/De ppo normal_sampled" -cd "/LinearSlope_20D" -c exp15
python main.py train -d "./experiments/De ppo normal_sampled" -cd "/SharpRidge_5D" -c exp16
python main.py train -d "./experiments/De ppo normal_sampled" -cd "/SharpRidge_10D" -c exp17
python main.py train -d "./experiments/De ppo normal_sampled" -cd "/SharpRidge_20D" -c exp18
python main.py train -d "./experiments/De ppo normal_sampled" -cd "/StepEllipsoidal_5D" -c exp19
python main.py train -d "./experiments/De ppo normal_sampled" -cd "/StepEllipsoidal_10D" -c exp20
python main.py train -d "./experiments/De ppo normal_sampled" -cd "/StepEllipsoidal_20D" -c exp21
python main.py train -d "./experiments/De ppo normal_sampled" -cd "/RosenbrockRotated_5D" -c exp22
python main.py train -d "./experiments/De ppo normal_sampled" -cd "/RosenbrockRotated_10D" -c exp23
python main.py train -d "./experiments/De ppo normal_sampled" -cd "/RosenbrockRotated_20D" -c exp24
python main.py train -d "./experiments/De ppo normal_sampled" -cd "/SchaffersIllConditioned_5D" -c exp25
python main.py train -d "./experiments/De ppo normal_sampled" -cd "/SchaffersIllConditioned_10D" -c exp26
python main.py train -d "./experiments/De ppo normal_sampled" -cd "/SchaffersIllConditioned_20D" -c exp27
python main.py train -d "./experiments/De ppo normal_sampled" -cd "/LunacekBiR_5D" -c exp28
python main.py train -d "./experiments/De ppo normal_sampled" -cd "/LunacekBiR_10D" -c exp29
python main.py train -d "./experiments/De ppo normal_sampled" -cd "/LunacekBiR_20D" -c exp30
python main.py train -d "./experiments/De ppo normal_sampled" -cd "/GG101me_5D" -c exp31
python main.py train -d "./experiments/De ppo normal_sampled" -cd "/GG101me_10D" -c exp32
python main.py train -d "./experiments/De ppo normal_sampled" -cd "/GG101me_20D" -c exp33
python main.py train -d "./experiments/De ppo normal_sampled" -cd "/GG21hi_5D" -c exp34
python main.py train -d "./experiments/De ppo normal_sampled" -cd "/GG21hi_10D" -c exp35
python main.py train -d "./experiments/De ppo normal_sampled" -cd "/GG21hi_20D" -c exp36