python main.py train -d "./experiments/De ppo normal_sampled" -cd "/AttractiveSector_20D" -c exp3
python main.py train -d "./experiments/De ppo normal_sampled" -cd "/BuecheRastrigin_20D" -c exp6
python main.py train -d "./experiments/De ppo normal_sampled" -cd "/DifferentPowers_20D" -c exp12
python main.py train -d "./experiments/De ppo normal_sampled" -cd "/LinearSlope_20D" -c exp15
python main.py train -d "./experiments/De ppo normal_sampled" -cd "/SharpRidge_5D" -c exp16
python main.py train -d "./experiments/De ppo normal_sampled" -cd "/SharpRidge_20D" -c exp18
python main.py train -d "./experiments/De ppo normal_sampled" -cd "/StepEllipsoidal_5D" -c exp19
python main.py train -d "./experiments/De ppo normal_sampled" -cd "/StepEllipsoidal_10D" -c exp20
python main.py train -d "./experiments/De ppo normal_sampled" -cd "/StepEllipsoidal_20D" -c exp21
python main.py train -d "./experiments/De ppo normal_sampled" -cd "/RosenbrockRotated_5D" -c exp22
python main.py train -d "./experiments/De ppo normal_sampled" -cd "/RosenbrockRotated_10D" -c exp23
python main.py train -d "./experiments/De ppo normal_sampled" -cd "/RosenbrockRotated_20D" -c exp24
python main.py train -d "./experiments/De ppo normal_sampled" -cd "/SchaffersIllConditioned_5D" -c exp25
python main.py train -d "./experiments/De ppo normal_sampled" -cd "/SchaffersIllConditioned_10D" -c exp26
python main.py train -d "./experiments/De ppo normal_sampled" -cd "/SchaffersIllConditioned_20D" -c exp27
python main.py train -d "./experiments/De ppo normal_sampled" -cd "/LunacekBiR_20D" -c exp30
python main.py train -d "./experiments/De ppo normal_sampled" -cd "/GG101me_20D" -c exp33
python main.py train -d "./experiments/De ppo normal_sampled" -cd "/GG21hi_20D" -c exp36